### ISSUE TITLE
YSI/Zeex Compiler

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI#1]
When I am using Zeex Compiler, I get this as the error: **include\YSI\y_master.inc(134) : fatal error 111: user error: Did you do <YSI/y_master> instead of the required <YSI\y_master>?**. Here is a list of my include list:

```
#include <a_samp>
#include <fixes>
#include <a_mysql>
#include <crashdetect>
#define MASTER 7
#include <YSI\y_master>
#include <YSI\y_commands>
#include <YSI\y_hooks>
// #include <YSI\y_timers>
#include <sscanf2>
#include <streamer>
#include <a_zones>
#include <foreach>
#include <EVF>
#include <cuffs>
#include <formatex>
```

Not sure what's wrong, but would be nice if anyone can help me solve it so I can use both. The compiler I am using is this [one](https://github.com/Zeex/pawn/releases) from the releases page, and date is 2016/07/02

**Comment by Y-Less** [comment]
This repository is massively out of date.  Use this one instead:

https://github.com/Misiur/YSI-Includes

**Comment by xFirez** [comment]
`include\YSI\..\YSI_Core\..\YSI_Coding\..\YSI_Core\..\YSI_Storage\..\YSI_Internal\amx_assembly.inc(38) : fatal error 111: user error: Please update "https://github.com/Zeex/amx_assembly" to get "deref()"`

Where do I put this amx_assembly stuff?
