### ISSUE TITLE
Missing arg in malloc_OnRunTimeError

### ISSUE THREAD

**Issue by fernando-guzman** [pawn-lang/YSI#4]
![issue](https://image.prntscr.com/image/4NKhNkmRTXGJLSB5NO-Jdw.png)

I am already using OnRunTimeError in another file

**Comment by Y-Less** [comment]
Ahh yeah.  Just add `, suppress` to that call.

**Comment by Y-Less** [comment]
No, don't.  Update YSI - that is apparently already fixed here:

https://github.com/Misiur/YSI-Includes

**Comment by fernando-guzman** [comment]
Thank you!
